CONTRIBUTING.md, README.md
=> Add readme and contributing docs

.travis.yml, ffi/primitives/mono_pkg.yaml, ffi/structs/mono_pkg.yaml, ffi/system-command/mono_pkg.yaml
This was disabled ahead of the 2.6 launch
=> run FFI against dev channel

ffi/README.md
=> update FFI readme for CMake

ffi/system-command/linux.dart, ffi/system-command/macos.dart, ffi/system-command/windows.dart
The documentation and the final result is https (and is good practice anyway).
=> Use https to match documentation

ffi/system-command/win32ui.dart
Proving out how to use Win32 UTF16 API from Dart.
=> Win32 MessageBox sample

ffi/README.md, ffi/system-command/README.md
=> add link to dart.dev FFI docs

ffi/primitives/primitives.dart, ffi/primitives/pubspec.yaml, ffi/structs/pubspec.yaml, ffi/structs/structs.dart, ffi/structs/structs_library/structs.c, ffi/structs/structs_library/structs.h, ffi/system-command/linux.dart, ffi/system-command/macos.dart, ffi/system-command/pubspec.yaml, ffi/system-command/win32ui.dart, ffi/system-command/windows.dart, ffi/test_utils/pubspec.yaml
=> Upgrade to FFI 1.0

ffi/README.md
https://github.com/dart-lang/sdk/issues/44934
=> [ffi] Add missing step in README

.github/workflows/container_docker_test.yml, .github/workflows/dart.yml, README.md, server/README.md, server/google_apis/.gitignore, server/google_apis/Dockerfile, server/google_apis/README.md, server/google_apis/bin/server.dart, server/google_apis/lib/helpers.dart, server/google_apis/mono_pkg.yaml, server/google_apis/pubspec.yaml, server/simple/.gitignore, server/simple/Dockerfile, server/simple/README.md, server/simple/bin/server.dart, server/simple/dart_test.yaml, server/simple/mono_pkg.yaml, server/simple/pubspec.yaml, server/simple/test/docker_test.dart, server/simple/test/server_test.dart, server/simple/test/test_definitions.dart, server/simple/tool/docker_test_script.sh
One basic shelf sample
One more complex sample demonstrating Google APIs from Cloud Run
Both include Dockerfiles
=> Dart + docker samples

server/google_apis/lib/helpers.dart
=> Small nit documentation on gcpProjectIdEnvironmentVariables

server/README.md, server/google_apis/README.md, server/simple/README.md, server/simple/bin/server.dart, server/simple/public/index.html, server/simple/test/test_definitions.dart
Update readmes
Improve inline documentation in bin/server.dart
Cleanup to inedx.html and tests
=> Update server/simple documentation

.github/workflows/container_docker_test.yml, .github/workflows/dart.yml, command_line/README.md, command_line/mono_pkg.yaml, extension_methods/mono_pkg.yaml, ffi/hello_world/mono_pkg.yaml, ffi/primitives/mono_pkg.yaml, ffi/structs/mono_pkg.yaml, ffi/system-command/README.md, ffi/system-command/mono_pkg.yaml, mono_repo.yaml, native_app/mono_pkg.yaml, server/google_apis/mono_pkg.yaml, server/simple/mono_pkg.yaml, server/simple/tool/docker_test_script.sh, tool/ci.sh
=> Update to the latest mono_repo

server/simple/README.md, server/simple/test/test_definitions.dart
=> Adding server run doc

.github/workflows/dart.yml, command_line/lib/src/options.g.dart, command_line/pubspec.yaml, extension_methods/example/code_generation.dart, extension_methods/example/core_type_extensions.dart, ffi/hello_world/hello.dart, ffi/primitives/primitives.dart, ffi/structs/structs.dart, ffi/system-command/linux.dart, ffi/system-command/macos.dart, ffi/system-command/win32ui.dart, ffi/system-command/windows.dart, ffi/test_utils/lib/test_utils.dart, ffi/test_utils/mono_pkg.yaml, null_safety/calculate_lix/bin/main.dart, null_safety/calculate_lix/lib/lix.dart, null_safety/calculate_lix/mono_pkg.yaml, server/google_apis/bin/server.dart, server/google_apis/pubspec.yaml, server/simple/bin/server.dart, server/simple/pubspec.yaml
Added mono_repo configuration to remaining packages
Cleaned up some unnecessary parens
Bumped pkg dependencies
shelf: move to extension methods over Pipeline for middleware/handler composition
=> More cleanup

README.md
Tweak the main readme to updates for isolates
=> Add isolates to readme to easily navigate to sample code

ffi/README.md
Remove reference to Dockerfiles that no longer exist
=> Update FFI readme

ffi/structs/structs.dart, ffi/structs/structs_library/CMakeLists.txt, ffi/structs/structs_library/structs.c, ffi/structs/structs_library/structs.def, ffi/structs/structs_library/structs.h, ffi/structs/test/structs_test.dart
small changes I made while studying FFI. seeing #145 I think we should update it.
=> * Fix small UseAfterFree issue * Add function that takes struct as parameter

server/simple/analysis_options.yaml, server/simple/bin/server.dart, server/simple/public/index.html, server/simple/test/docker_test.dart, server/simple/test/server_test.dart
Also some tweaks to analysis options
=> server/simple: add an info iframe to sample web page

ffi/primitives/primitives.dart, ffi/primitives/primitives_library/primitives.c, ffi/primitives/primitives_library/primitives.def, ffi/primitives/primitives_library/primitives.h, ffi/primitives/test/primitives_test.dart
Closes https://github.com/dart-lang/samples/issues/152
=> Remove FFI varargs example

.github/dependabot.yml, .github/workflows/container_docker_test.yml, .github/workflows/dart.yml, tool/ci.sh
=> blast_repo fixes

.github/workflows/dart.yml, tool/ci.sh
=> Latest GitHub Actions

isolates/README.md, isolates/bin/send_and_receive.dart, isolates/pubspec.yaml
=> Updates "send and receive" isolate example to use Isolate.run

.github/workflows/dart.yml, tool/ci.sh
Closes https://github.com/dart-lang/samples/pull/171
=> Latest CI actions

.github/workflows/container_docker_test.yml, .github/workflows/dart.yml, mono_repo.yaml, tool/ci.sh
Also updates actions versions used in other workflows and accounts for switch to `main` branch.
=> Regenerate CI with latest mono_repo

.github/workflows/dart.yml, command_line/pubspec.yaml, enhanced_enums/pubspec.yaml, extension_methods/pubspec.yaml, ffi/hello_world/pubspec.yaml, ffi/primitives/pubspec.yaml, ffi/structs/pubspec.yaml, ffi/structs/structs.dart, ffi/system-command/pubspec.yaml, ffi/test_utils/pubspec.yaml, isolates/pubspec.yaml, native_app/pubspec.yaml, null_safety/calculate_lix/pubspec.yaml, package_constraint_solver/pubspec.yaml, parameters/pubspec.yaml, server/google_apis/pubspec.yaml, server/simple/pubspec.yaml, tool/ci.sh
Updates SDK constraints, mono_repo and actions files, and minimal fixes to get analysis running.
\cc @johnpryan
=> Initial migration to Dart 3

package_constraint_solver/README.md
- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.
---
<details>
<summary>Contribution guidelines:</summary><br>
- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- …
=> constraint_solver: remove test coverage badge from readme
